atividades/urls.py
from django.urls import path
from .views import favoritar_livro, favoritos, reservar_livro, reservas

app_name = 'atividades'


urlpatterns = [
    path('favoritar_livro/<int:livro_id>/', favoritar_livro, name='favoritar_livro'),
    path('reservar_livro/<int:livro_id>/', reservar_livro, name='reservar_livro'),
    path('reservas/', reservas, name='reservas'),
    path('favoritos/', favoritos, name='favoritos'),
]

bibliotecaDjango/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

from bibliotecaDjango import settings
from django.conf.urls.static import static 
from livros import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('atividades/', include('atividades.urls')),
    path('', views.index, name='index'),
    path('letra/<str:letra>/', views.index, name='index_com_letra'),
    path('livro/<int:id>', views.ver_livro, name='ver_livro'),
    path('livros/editar/<int:id>/', views.editar_livro, name='editar_livro'),
    path('deletar_livro/<int:pk>/', views.deletar_livro, name='deletar_livro'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/editar/<int:id>/', views.editar_categoria, name='editar_categoria'),
    path('deletar_categoria/<int:pk>/', views.deletar_categoria, name='deletar_categoria'),
    path('colecoes/', views.colecoes, name='colecoes'),
    path('colecoes/editar/<int:id>/', views.editar_colecao, name='editar_colecao'),
    path('deletar_colecao/<int:pk>/', views.deletar_colecao, name='deletar_colecao'),
    path('autores/', views.autores, name='autores'),
    path('autores/editar/<int:id>/', views.editar_autor, name='editar_autor'),
    path('deletar_autor/<int:pk>/', views.deletar_autor, name='deletar_autor'),
    path('sobre/', views.sobre, name='sobre'),
]

if settings.DEBUG:  # Apenas para o modo de desenvolvimento
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('perfil/', views.perfil, name='perfil'),
]

livros/models.py
from django.db import models
from pydantic import ValidationError

# Create your models here.

# Tema do projeto: Biblioteca
# # Dev: Álvaro Victor Carlos Parente - IFSalgueiro

class Livro(models.Model):
    nome = models.CharField(max_length=255)
    autor = models.ForeignKey('Autor', on_delete=models.CASCADE, related_name="livros")
    ano = models.PositiveIntegerField()
    sinopse = models.TextField(blank=True, null=True, verbose_name="Sinopse:")
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)
    colecao = models.ForeignKey('Colecao', on_delete=models.SET_NULL, null=True, blank=True, related_name="livros")
    imagem = models.ImageField(upload_to='livros/', null=True, blank=True)
    is_reservado = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True)
    
    def clean(self):
        super().clean()
        if self.ano > 2025:
            raise ValidationError({f'ano': "O ano não pode ser maior que 2025."})

    def __str__(self):
        return self.nome
    
class Categoria(models.Model):
    nome = models.CharField(max_length=255, unique=True, verbose_name="Nome da Categoria:")
    descricao = models.TextField(blank=True, null=True, verbose_name="Descrição:")
    data_criacao = models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação:")
    data_atualizacao = models.DateTimeField(auto_now=True, verbose_name="Data de Atualização:")
    
    def __str__(self):
        return self.nome
    
class Autor(models.Model):
    nome = models.CharField(max_length=255, unique= True, verbose_name="Nome do Autor(A):")
    biografia = models.TextField(blank= True, null=True, verbose_name="Biografia do Autor(a):")
    aniversario = models.DateField(verbose_name="Data de Nascimento:")
    nacionalidade = models.CharField(max_length=100, verbose_name="Nacionalidade:")
    data_criacao = models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação:")
    data_atualizacao = models.DateTimeField(auto_now=True, verbose_name="Data de Atualização:")
    
    def clean(self):
        super().clean()
        if self.aniversario.year >= 2022:
            raise ValidationError({f'aniversario': "O ano de nasicmento não pode ser maior que 2021."})

    def __str__(self):
        return self.nome
    
class Colecao(models.Model):
    nome = models.CharField(max_length=255, unique= True, verbose_name="Nome da Coleção:")
    descricao = models.TextField(blank= True, null=True, verbose_name="Descrição:")
    data_criacao = models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação:")
    data_atualizacao = models.DateTimeField(auto_now=True, verbose_name="Data de Atualização:")

    def __str__(self):
        return self.nome
    
    

livros/forms.py
from django import forms
from .models import Autor, Categoria, Colecao, Livro

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = ['nome', 'autor', 'ano', 'sinopse', 'categoria', 'colecao', 'imagem']  
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
            'autor': forms.Select(attrs={'class': 'form-addlivro'}),
            'ano': forms.NumberInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
            'sinopse': forms.TextInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
            'categoria': forms.Select(attrs={'class': 'form-addlivro'}),
            'colecao': forms.Select(attrs={'class': 'form-addlivro'}),
            'imagem': forms.FileInput(attrs={'class': 'form-addlivro'}),
        }
        labels = {
            'nome': 'Nome do Livro:',
            'autor': 'Autor:',
            'ano': 'Ano:',
            'sinopse' : 'Sinopse',
            'categoria': 'Categoria:',
            'colecao': 'Coleção:',
            'imagem': 'Imagem do Livro:',
        }
        
class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome', 'descricao']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
            'descricao': forms.TextInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
        }
        labels = {
            'nome': 'Nome da Categoria',
            'descricao': 'Descrição',
        }
        
class AutorForm(forms.ModelForm):
    class Meta:
        model = Autor
        fields = ['nome', 'biografia', 'aniversario', 'nacionalidade']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
            'biografia': forms.TextInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
            'aniversario': forms.DateInput(attrs={'class': 'form-addlivro', 'required': 'required', 'type': 'date'}),
            'nacionalidade': forms.TextInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
        }
        labels = {
            'nome': 'Nome do Autor',
            'biografia': 'Biografia',
            'aniversario': 'Data de Aniversário',
            'nacionalidade': 'Nacionalidade',
        }

class ColecaoForm(forms.ModelForm):
    class Meta:
        model = Colecao
        fields = ['nome', 'descricao']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
            'descricao': forms.TextInput(attrs={'class': 'form-addlivro', 'required': 'required'}),
            
        }
        labels = {
            'nome': 'Nome da coleção:',
            'descricao': 'Descrição da coleção:',
            
        }

livros/views.py
from django.shortcuts import get_object_or_404, redirect, render
from atividades.models import Favorito, Reserva
from livros.forms import AutorForm, CategoriaForm, ColecaoForm, LivroForm
from livros.models import Autor, Categoria, Colecao, Livro
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator



@login_required(login_url='/usuarios/login/')
def index(request, letra=None):

    livro_form = LivroForm()
    livros = Livro.objects.all()
    colecoes = Colecao.objects.all().order_by("nome")
    autores = Autor.objects.all().order_by("nome")

    if letra is None or letra == 'TODOS':
        livros = Livro.objects.all()  
    elif letra == '123':
        livros = Livro.objects.filter(nome__regex=r'^\d')  
    else:
        livros = Livro.objects.filter(nome__istartswith=letra) 

    colecao_pesquisa = request.GET.get('colecao_pesquisa')  
    autor_pesquisa = request.GET.get('autor_pesquisa')     
    texto_pesquisa = request.GET.get('q', '')

    if texto_pesquisa: 
        
        livros = livros.filter(nome__icontains=texto_pesquisa)
        
    if colecao_pesquisa:
        livros = livros.filter(colecao=colecao_pesquisa)

    if autor_pesquisa:
        livros = livros.filter(autor=autor_pesquisa)

    if request.method == "POST":
        if  'salvar_livro' in request.POST:
            livro_form = LivroForm(request.POST, request.FILES)
            if livro_form.is_valid():
                livro_form.save()
                return redirect('index')

    
    livros = livros.order_by("id")
    paginator = Paginator(livros, 10)
    pagina_num = request.GET.get("page")
    livros = paginator.get_page(pagina_num)
    
    livros_favoritos_ids = Favorito.objects.filter(user=request.user).values_list('livro_id', flat=True)
    livros_reservados_ids = Reserva.objects.filter(user=request.user).values_list('livro_id', flat=True)
    
    
    return render(request, 'index.html', {
        'livro_form': livro_form,
        'livros': livros,
        'colecoes' : colecoes,
        'autores' : autores,
        'letra': letra,
        'livros_favoritos': livros_favoritos_ids,
        'livros_reservados': livros_reservados_ids,
    })

    
    
def ver_livro(request, id):
    
    livro = get_object_or_404(Livro, id= id)
    
    livros_relacionados = Livro.objects.filter(
        colecao=livro.colecao,
        categoria=livro.categoria
    ).exclude(id=livro.id)
    
    livros_favoritos_ids = Favorito.objects.filter(user=request.user).values_list('livro_id', flat=True)
    livros_reservados_ids = Reserva.objects.filter(user=request.user).values_list('livro_id', flat=True)

    return render(request, 'livros/listar/ver_livro.html', {
        'livro': livro,
        'livros_relacionados': livros_relacionados,
        'livros_favoritos': livros_favoritos_ids,
        'livros_reservados': livros_reservados_ids,
    })

def editar_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    if request.method == 'POST':
        form = LivroForm(request.POST, request.FILES, instance=livro)
        if form.is_valid():
            form.save()
            return redirect('ver_livro', id= livro.id)
        
    else:
        form = LivroForm(instance=livro)

    return render(request, 'livros/editar/editar_livro.html', {'form': form, 'livro': livro})

def deletar_livro(request, pk):
    livro = get_object_or_404(Livro, pk=pk)

    if request.method == "POST":
        if 'confirmar' in request.POST:
            livro.delete()
            return redirect('index') 

    return render(request, 'livros/deletar/deletar_livro.html', {'livro': livro})

def categorias(request):
    categoria_form = CategoriaForm()
    
    if request.method == "POST":
        if 'salvar_categoria' in request.POST:
            categoria_form = CategoriaForm(request.POST)
            if categoria_form.is_valid():
                categoria_form.save()
                return redirect('categorias')
            
    categorias = Categoria.objects.all().order_by("nome")
    
    return render(request, 'livros/listar/categorias.html', {
        'categoria_form': categoria_form,
        'categorias': categorias,
    })

def editar_categoria(request, id):
    categoria = get_object_or_404(Categoria, id=id)
    if request.method == 'POST':
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            return redirect('categorias') 
    else:
        form = CategoriaForm(instance=categoria)

    return render(request, 'livros/editar/editar_categoria.html', {'form': form, 'categoria': categoria})

def deletar_categoria(request, pk):
    categoria = get_object_or_404(Categoria, pk=pk)

    if request.method == "POST":
        if 'confirmar' in request.POST:
            categoria.delete()
            return redirect('categorias') 

    return render(request, 'livros/deletar/deletar_categoria.html', {'categoria': categoria})

def colecoes(request):
    
    colecao_form = ColecaoForm()
    
    if request.method == "POST":
        if 'salvar_colecao' in request.POST:
            colecao_form = ColecaoForm(request.POST)
            if colecao_form.is_valid():
                colecao_form.save()
                return redirect('colecoes')
            
    colecoes = Colecao.objects.prefetch_related('livros').all().order_by("nome")
    
    return render(request, 'livros/listar/colecoes.html', {
        'colecao_form': colecao_form,
        'colecoes': colecoes,
    })
    
def editar_colecao(request, id):
    colecao = get_object_or_404(Colecao, id=id)
    if request.method == 'POST':
        form = ColecaoForm(request.POST, instance=colecao)
        if form.is_valid():
            form.save()
            return redirect('colecoes') 
    else:
        form = ColecaoForm(instance=colecao)

    return render(request, 'livros/editar/editar_colecao.html', {'form': form, 'colecao': colecao})

def deletar_colecao(request, pk):
    colecao = get_object_or_404(Colecao, pk=pk)

    if request.method == "POST":
        if 'confirmar' in request.POST:
            colecao.delete()
            return redirect('colecoes') 

    return render(request, 'livros/deletar/deletar_colecao.html', {'colecao': colecao})
    
def autores(request):
    autor_form = AutorForm()
    
    if request.method == "POST":

        if 'salvar_autor' in request.POST:
            autor_form = AutorForm(request.POST)
            if autor_form.is_valid():
                autor_form.save()
                return redirect('autores')
   
    autores = Autor.objects.prefetch_related('livros').all()
    
    return render(request, 'livros/listar/autores.html', {
        'autor_form': autor_form,
        'autores': autores,
    })
    
def editar_autor(request, id):
    autor = get_object_or_404(Autor, id=id)
    if request.method == 'POST':
        form = AutorForm(request.POST, instance=autor)
        if form.is_valid():
            form.save()
            return redirect('autores') 
    else:
        form = AutorForm(instance=autor)

    return render(request, 'livros/editar/editar_autor.html', {'form': form, 'autor': autor})

def deletar_autor(request, pk):
    autor = get_object_or_404(Autor, pk=pk)

    if request.method == "POST":
        if 'confirmar' in request.POST:
            autor.delete()
            return redirect('autores') 

    return render(request, 'livros/deletar/deletar_autor.html', {'autor': autor})


def sobre(request):
    
    return render(request, 'about.html' )

templates/livros/listar/autores.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca - Autores</title>

    
    {% load static %}

    
    <link rel="stylesheet" href="{% static 'css/livros/listar/autores.css' %}">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>

<body>

    
    {% include 'navbar.html' %}

    <!-- Modal novo autor -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content"
                style="background: url('{% static 'images/card_modal.png' %}') no-repeat center center !important; background-size: 80% auto !important; height: 700px; border: 0; padding: 100px;">
                <div class="modal-body">
                    <div style="display: flex; align-items: end; justify-content: flex-end; width: 105%;">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <br>
                    <h4 style="font-family: MedievalSharp, cursive;
                    font-weight: bold;
                    font-style: normal;
                    color: #5a4d3e;">NOVO AUTOR+</h4>
                    <br>
                    <form class="form-addlivro" method="post">
                        {% csrf_token %}
                        <label for="{{ autor_form.nome.id_for_label }}">Nome do Autor:</label>
                        {{ autor_form.nome }}
                        
                        <label for="{{ autor_form.biografia.id_for_label }}">Biografia:</label>
                        {{ autor_form.biografia }}
                        
                        <label for="{{ autor_form.aniversario.id_for_label }}">Data de Aniversário:</label>
                        {{ autor_form.aniversario }}
                        
                        <label for="{{ autor_form.nacionalidade.id_for_label }}">Nacionalidade:</label>
                        {{ autor_form.nacionalidade }}
                        
                        <button name="salvar_autor" type="submit"><u>ADICIONAR</u></button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <main>
        <div class="main-actions">
            <h2>AUTORES</h2>
            {% if request.user.is_superuser %}
                            
            <button class="button-aplicar-filtros" style=" background: url('{% static 'images/card_button.png' %}') no-repeat center center !important;" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">NOVO AUTOR+</button>
                            {% endif %}
        </div>
        

        <div class="main-categorias">
            {% for autor in autores %}
            <div style="display:flex; justify-content: space-between; align-items:center; margin-top: 20px">   
                <h4>{{autor.nome}}</h4>
                {% if request.user.is_superuser %}
                <div class="main-icons">
                    <a style="color: #5a4d3e;" href="{% url 'editar_autor' autor.id %}">
                        <i style="color: #5a4d3e;" class="bi bi-pencil-square"></i> 
                    </a>
                    <a style="color: #5a4d3e;" href="{% url 'deletar_autor' autor.id %}">
                        <i  class="bi bi-trash3-fill"></i>
                    </a>
                </div>
                            
                            {% endif %}
            </div>
        <p>{{ autor.biografia }}</p>
        <span><strong>Nacionalidade:</strong> {{ autor.nacionalidade }}</span><br>
        <span><strong>Aniversário:</strong> {{ autor.aniversario }}</span><br>

        <strong>Livros:</strong>
        {% if autor.livros.all %}
            <ul>
                {% for livro in autor.livros.all %}
                    <li>{{ livro.nome }} ({{ livro.ano }})</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Este autor ainda não tem livros registrados.</p>
        {% endif %}
        
        <hr>
    {% endfor %}
        </div><br>
        
    </main>

</body>

</html>

templates/livros/listar/categorias.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca - Categorias</title>

    
    {% load static %}

    
    <link rel="stylesheet" href="{% static 'css/livros/listar/categorias.css' %}">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>

<body>

    {% include 'navbar.html' %}


     <!-- Modal nova categoria -->
     <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content"
                style="background: url('{% static 'images/card_modal.png' %}') no-repeat center center !important; background-size: 80% auto !important; height: 700px; border: 0; padding: 100px;">
                <div class="modal-body">
                    <div style="display: flex; align-items: end; justify-content: flex-end; width: 105%;">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <br>
                    <h4 style="font-family: MedievalSharp, cursive;
                    font-weight: bold;
                    font-style: normal;
                    color: #5a4d3e;">NOVA CATEGORIA+</h4>
                    <br>
                    <form class="form-addlivro" method="post">
                        {% csrf_token %}
                        <label for="id_nome">Nome da Categoria:</label>
                        {{ categoria_form.nome }}
                    
                        <label for="id_descricao">Descrição:</label>
                        {{ categoria_form.descricao }}
                        
                        
                        <button name="salvar_categoria" type="submit"><u>ADICIONAR</u></button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>

    <main>
        <div class="main-actions">
            <h2>CATEGORIAS</h2>
            {% if request.user.is_superuser %}
                            
            <button class="button-aplicar-filtros" style=" background: url('{% static 'images/card_button.png' %}') no-repeat center center !important;" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">NOVA CATEGORIA+</button>
            {% endif %}
        </div>
        

        <div class="main-categorias">
            {% for categoria in categorias %}
            
             
            <div style="display:flex; justify-content: space-between; align-items:center; margin-top: 20px">   
                <h4>{{categoria.nome}}</h4>
                {% if request.user.is_superuser %}
                            
                <div class="main-icons">
                    <a style="color: #5a4d3e;" href="{% url 'editar_categoria' categoria.id %}">
                        <i style="color: #5a4d3e;" class="bi bi-pencil-square"></i> 
                    </a>
                    <a style="color: #5a4d3e;" href="{% url 'deletar_categoria' categoria.id %}">
                        <i  class="bi bi-trash3-fill"></i>
                    </a>
                </div>
                            {% endif %}
            </div>
            <hr style="margin-top: -7px">
            <span>{{categoria.descricao}}</span>
            {% endfor %}
        </div><br>
        
    </main>

</body>

</html>

templates/livros/listar/ver_livro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}

    <title>{{livro.nome}}</title>
    <link rel="stylesheet" href="{% static 'css/livros/listar/ver_livro.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body >
    {% include 'navbar.html' %}


<article>
    <main>

        <div class="livro-container">
            <img src="{{ livro.imagem.url }}" alt="{{ livro.nome }}" class="livro-imagem">
            
            
            <form action="{% url 'atividades:favoritar_livro' livro.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="livro_id" value="{{ livro.id }}">
                <button name="favoritar" type="submit" class="favorite-btn {% if livro.id in livros_favoritos %} favorited {% endif %}">
                    ♥
                </button>
            </form>

        </div>
        <div>
            <actions style=" margin-top: 20px;">   
                <h4>{{livro.nome}}</h4>
                {% if request.user.is_superuser %}
                            
                <div class="main-icons">
                    <a style="color: #5a4d3e;" href="{% url 'editar_livro' livro.id %}">
                        <i style="color: #5a4d3e;" class="bi bi-pencil-square"></i> 
                    </a>
                    <a style="color: #5a4d3e;" href="{% url 'deletar_livro' livro.id %}">
                        <i  class="bi bi-trash3-fill"></i>
                    </a>
                </div>
                            {% endif %}
            </actions>
            <hr>
            <span>{{livro.sinopse}}</span>
            <section>
                <span><strong>Autor(a): </strong>{{livro.autor.nome}}</span>
                <span><strong>Ano: </strong>{{livro.ano}}</span>
                <span><strong>Categoria: </strong>{{livro.categoria.nome}}</span>
                <span><strong>Coleção: </strong>{{livro.colecao.nome}}</span>
            </section>

            <form action="{% url 'atividades:reservar_livro' livro.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="livro_id" value="{{ livro.id }}">

                {% if livro.is_reservado %}
                    {% if livro.id in livros_reservados %}
                        <button class="button-aplicar-filtros btn-cancelar" style="border-radius: 5px" type="submit">DEVOLVER</button>
                    {% else %}
                        <span class="btn-indisponivel" type="button">INDISPONÍVEL</span>
                    {% endif %}
                {% else %}
                    <button class="button-aplicar-filtros btn-reservar" 
                    style="background: url('{% static 'images/card_button.png' %}') no-repeat center center !important; border-radius: 5px" 
                    type="submit">RESERVAR</button>
                {% endif %}

            </form>
        </div>
    </main>
    
    <footer>
    <h4>Outros títulos que talvez você se interesse</h4>
    <search>
        {% for livro in livros_relacionados %}
            <a style="text-decoration:none" href="{% url 'ver_livro' livro.id %}">
                <div class="livro-exemple">
                    {% if livro.imagem %}
                    <div class="livro-container">
                        <img src="{{ livro.imagem.url }}" alt="{{ livro.nome }}" class="livro-imagem" style="max-width:100px">
                        
                        
                        <form action="{% url 'atividades:favoritar_livro' livro.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="livro_id" value="{{ livro.id }}">
                            <button name="favoritar" type="submit" class="favorite-btn {% if livro.id in livros_favoritos %} favorited {% endif %}">
                                ♥
                            </button>
                        </form>
            
                    </div>
                    {% else %}
                        Sem imagem
                    {% endif %}
                    <span>{{ livro.nome }}</span>
                    <i>{{ livro.autor.nome }}</i>
                </div>
            <a/>
            {% endfor %}
    </search>
</footer>

</article>

    
</body>
</html>