bibliotecaDjango/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

from bibliotecaDjango import settings
from django.conf.urls.static import static 
from livros import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('atividades/', include('atividades.urls')),
    path('', views.index, name='index'),
    path('letra/<str:letra>/', views.index, name='index_com_letra'),
    path('livro/<int:id>', views.ver_livro, name='ver_livro'),
    path('livros/editar/<int:id>/', views.editar_livro, name='editar_livro'),
    path('deletar_livro/<int:pk>/', views.deletar_livro, name='deletar_livro'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/editar/<int:id>/', views.editar_categoria, name='editar_categoria'),
    path('deletar_categoria/<int:pk>/', views.deletar_categoria, name='deletar_categoria'),
    path('colecoes/', views.colecoes, name='colecoes'),
    path('colecoes/editar/<int:id>/', views.editar_colecao, name='editar_colecao'),
    path('deletar_colecao/<int:pk>/', views.deletar_colecao, name='deletar_colecao'),
    path('autores/', views.autores, name='autores'),
    path('autores/editar/<int:id>/', views.editar_autor, name='editar_autor'),
    path('deletar_autor/<int:pk>/', views.deletar_autor, name='deletar_autor'),
    path('sobre/', views.sobre, name='sobre'),
]

if settings.DEBUG:  # Apenas para o modo de desenvolvimento
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('perfil/', views.perfil, name='perfil'),
]

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password

class RegisterForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        error_messages={
            'invalid': 'Digite um endereço de e-mail válido.',
            'required': 'O campo de e-mail é obrigatório.'
        }
    )
    
    is_superuser = forms.ChoiceField(
        choices=[(False, 'Usuário comum'), (True, 'Superusuário')],
        widget=forms.Select(attrs={'class': 'select-custom'}),
        required=True,
        label="Tipo de Conta"
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'is_superuser']
        error_messages = {
            'username': {
                'required': 'O nome de usuário é obrigatório.',
                'unique': 'Este nome de usuário já está em uso.',
                'invalid': 'Digite um nome de usuário válido.',
                'max_length': 'O nome de usuário deve ter no máximo 150 caracteres.'
            },
            'password2': {
                'required': 'A confirmação da senha é obrigatória.',
                'password_mismatch': 'As senhas não coincidem.'
            }
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Este e-mail já está em uso. Tente outro.")
        return email

    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        try:
            validate_password(password)
        except ValidationError as e:
            raise ValidationError([
                erro.replace("This password", "A senha").replace("too common", "muito comum")
                .replace("too short", "muito curta (mínimo de 8 caracteres)")
                .replace("entirely numeric", "não pode ser composta apenas por números")
                for erro in e.messages
            ])
        return password

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

from atividades.models import Favorito, Reserva
from livros.models import Livro
from .forms import RegisterForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                
                return redirect('index')
           
    else:
        form = AuthenticationForm()
    
    return render(request, 'usuarios/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False) 
            user.is_superuser = form.cleaned_data.get('is_superuser') == 'True'  
            user.is_staff = user.is_superuser  
            user.save()  
            return redirect('usuarios:login')

    else:
        form = RegisterForm()
    
    return render(request, 'usuarios/register.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('usuarios:login')


def perfil(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)  
            return redirect('usuarios:perfil') 
    else:
        form = PasswordChangeForm(user=request.user)

    livros  = Favorito.objects.filter(user=request.user)
    reservados = Reserva.objects.filter(user=request.user)
    
    return render(request, 'usuarios/perfil.html', {'form': form, 'livros' : livros, 'reservados' : reservados})

templates/usuarios/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/usuarios/login.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body style="background-image: url('{% static "images/background_login.png" %}');">

    <form method="post">
        {% csrf_token %}
        <span class="title">ENTRAR</span>

        
        <div class="input-main">
            <span>Usuário:</span>
            <div class="input-action">
                <i class="bi bi-person-fill"></i>
                <input type="text" name="username" placeholder="Digite seu usuário:" required>
            </div>
            <hr>
        </div>
        <div class="input-main">
            <span>Senha:</span>
            <div class="input-action">
                <i class="bi bi-lock-fill"></i>
                <input type="password" name="password" placeholder="Digite sua senha:" required>
            </div>
            <hr>
        </div>
        {% if form.errors %}
            <div class="error-msg">
                <p>Usuário ou senha inválidos. Tente novamente.</p>
            </div>
        {% endif %}
        <div class="options">
            <button type="submit"><u>LOGAR</u></button>
            <span>ou</span>
            <span>Ainda não tem conta? <a href="{% url 'usuarios:register' %}">Cadastre-se</a></span>
        </div>
    </form>

</body>
</html>

templates/usuarios/perfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}

    <title>{{user.username}}</title>
    <link rel="stylesheet" href="{% static 'css/usuarios/perfil.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body >
    {% include 'navbar.html' %}

    <main>
        <div class="user-info">
            <i class="bi bi-person-circle"></i>
            <div class="user-details">
                <span><strong>{{user.username}}</strong>, Superusuário</span>
                <span style="font-size: 20px"><strong>E-mail: </strong>{{user.email}}</span>
                <span style="font-size: 20px"><strong>Último Login: </strong>{{user.last_login}}</span>
            </div>
        </div>
    
        <strong>Alterar Senha</strong>
        <form method="post">
            {% csrf_token %}
            
        
            {% if form.errors %}
                <div class="error-msg">
                    <p>Corrija os erros abaixo:</p>
                    {{ form.errors }}
                </div>
            {% endif %}
        
            <div class="input-main">
                <span>Senha atual:</span>
                <div class="input-action">
                    <i class="bi bi-lock-fill"></i>
                    {{ form.old_password }}
                </div>
                <hr>
            </div>
        
            <div class="input-main">
                <span>Nova senha:</span>
                <div class="input-action">
                    <i class="bi bi-lock-fill"></i>
                    {{ form.new_password1 }}
                </div>
                <hr>
            </div>
        
            <div class="input-main">
                <span>Confirme a nova senha:</span>
                <div class="input-action">
                    <i class="bi bi-lock-fill"></i>
                    {{ form.new_password2 }}
                </div>
                <hr>
            </div>
        
            <button class="btn-senha" type="submit">Salvar</button>
        </form><br>

        <strong>Títulos Reservados</strong>
        <search>
            {% for reservado in reservados %}
    <a style="text-decoration:none" href="{% url 'ver_livro' reservado.livro.id %}">
        <div class="livro-exemple">
            {% if reservado.livro.imagem %}
                <img src="{{ reservado.livro.imagem.url }}" alt="{{ reservado.livro.nome }}" style="max-width: 100px;">
            {% else %}
                Sem imagem
            {% endif %}
            <span>{{ reservado.livro.nome }}</span>
            <i>{{ reservado.livro.autor.nome }}</i>
        </div>
    </a>
{% endfor %}

        </search>
        
       
        
        <strong>Títulos marcados como Gostei</strong>
        <search>
            {% for favorito in livros %}
    <a style="text-decoration:none" href="{% url 'ver_livro' favorito.livro.id %}">
        <div class="livro-exemple">
            {% if favorito.livro.imagem %}
                <img src="{{ favorito.livro.imagem.url }}" alt="{{ favorito.livro.nome }}" style="max-width: 100px;">
            {% else %}
                Sem imagem
            {% endif %}
            <span>{{ favorito.livro.nome }}</span>
            <i>{{ favorito.livro.autor.nome }}</i>
        </div>
    </a>
{% endfor %}

        </search>
        
    </main>


    
</body>
</html>

templates/usuarios/register.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <link rel="stylesheet" href="{% static 'css/usuarios/login.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body style="background-image: url('{% static "images/background_login.png" %}');">

    <form style="margin-bottom: 80px" method="post">
        {% csrf_token %}
        <span class="title">CADASTRAR</span>

        
        <div class="input-main">
            <span>Usuário:</span>
            <div class="input-action">
                <i class="bi bi-person-fill"></i>
                <input type="text" name="username" placeholder="Digite seu usuário:" required>
            </div>
            <hr>
        </div>
        <div class="input-main">
            <span>E-mail:</span>
            <div class="input-action">
                <i class="bi bi-envelope-fill"></i>
                <input type="email" name="email" placeholder="Digite seu e-mail:" required>
            </div>
            <hr>
        </div>
        <div class="input-main">
            <span>Tipo de Conta:</span>
            <div class="input-action">
                <i class="bi bi-person-badge-fill"></i>
                {{ form.is_superuser }}
            </div>
            <hr>
            <span style="font-size: 15px; color: black"> *Com Super Usuário, poderá cadastrar, editar e deletar objetos do site.</span>
        </div>        
        <div class="input-main">
            <span>Senha:</span>
            <div class="input-action">
                <i class="bi bi-lock-fill"></i>
                <input type="password" name="password1" placeholder="Digite sua senha:" required>
            </div>
            <hr>
        </div>
        <div class="input-main">
            <span>Confirme sua Senha:</span>
            <div class="input-action">
                <i class="bi bi-lock-fill"></i>
                <input type="password" name="password2" placeholder="Digite novamente sua senha:" required>
            </div>
            <hr>
        </div>
        {% if form.errors %}
            <div style="font-size: 15px; color: black" class="error-msg">
                <p>Corrija os erros abaixo:</p>
                {{ form.errors }}
            </div>
        {% endif %}
        <div class="options">
            <button type="submit"><u>CRIAR CONTA</u></button>
            <span>ou</span>
            <span>Já tem conta? <a href="{% url 'usuarios:login' %}">Entrar</a></span>
        </div>
    </form>

</body>
</html>