atividades/urls.py
from django.urls import path
from .views import favoritar_livro, favoritos, reservar_livro, reservas

app_name = 'atividades'


urlpatterns = [
    path('favoritar_livro/<int:livro_id>/', favoritar_livro, name='favoritar_livro'),
    path('reservar_livro/<int:livro_id>/', reservar_livro, name='reservar_livro'),
    path('reservas/', reservas, name='reservas'),
    path('favoritos/', favoritos, name='favoritos'),
]

bibliotecaDjango/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

from bibliotecaDjango import settings
from django.conf.urls.static import static 
from livros import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('atividades/', include('atividades.urls')),
    path('', views.index, name='index'),
    path('letra/<str:letra>/', views.index, name='index_com_letra'),
    path('livro/<int:id>', views.ver_livro, name='ver_livro'),
    path('livros/editar/<int:id>/', views.editar_livro, name='editar_livro'),
    path('deletar_livro/<int:pk>/', views.deletar_livro, name='deletar_livro'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/editar/<int:id>/', views.editar_categoria, name='editar_categoria'),
    path('deletar_categoria/<int:pk>/', views.deletar_categoria, name='deletar_categoria'),
    path('colecoes/', views.colecoes, name='colecoes'),
    path('colecoes/editar/<int:id>/', views.editar_colecao, name='editar_colecao'),
    path('deletar_colecao/<int:pk>/', views.deletar_colecao, name='deletar_colecao'),
    path('autores/', views.autores, name='autores'),
    path('autores/editar/<int:id>/', views.editar_autor, name='editar_autor'),
    path('deletar_autor/<int:pk>/', views.deletar_autor, name='deletar_autor'),
    path('sobre/', views.sobre, name='sobre'),
]

if settings.DEBUG:  # Apenas para o modo de desenvolvimento
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('perfil/', views.perfil, name='perfil'),
]

livros/models.py
from django.db import models
from pydantic import ValidationError

# Create your models here.

# Tema do projeto: Biblioteca
# # Dev: Álvaro Victor Carlos Parente - IFSalgueiro

class Livro(models.Model):
    nome = models.CharField(max_length=255)
    autor = models.ForeignKey('Autor', on_delete=models.CASCADE, related_name="livros")
    ano = models.PositiveIntegerField()
    sinopse = models.TextField(blank=True, null=True, verbose_name="Sinopse:")
    categoria = models.ForeignKey('Categoria', on_delete=models.CASCADE)
    colecao = models.ForeignKey('Colecao', on_delete=models.SET_NULL, null=True, blank=True, related_name="livros")
    imagem = models.ImageField(upload_to='livros/', null=True, blank=True)
    is_reservado = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True)
    
    def clean(self):
        super().clean()
        if self.ano > 2025:
            raise ValidationError({f'ano': "O ano não pode ser maior que 2025."})

    def __str__(self):
        return self.nome
    
class Categoria(models.Model):
    nome = models.CharField(max_length=255, unique=True, verbose_name="Nome da Categoria:")
    descricao = models.TextField(blank=True, null=True, verbose_name="Descrição:")
    data_criacao = models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação:")
    data_atualizacao = models.DateTimeField(auto_now=True, verbose_name="Data de Atualização:")
    
    def __str__(self):
        return self.nome
    
class Autor(models.Model):
    nome = models.CharField(max_length=255, unique= True, verbose_name="Nome do Autor(A):")
    biografia = models.TextField(blank= True, null=True, verbose_name="Biografia do Autor(a):")
    aniversario = models.DateField(verbose_name="Data de Nascimento:")
    nacionalidade = models.CharField(max_length=100, verbose_name="Nacionalidade:")
    data_criacao = models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação:")
    data_atualizacao = models.DateTimeField(auto_now=True, verbose_name="Data de Atualização:")
    
    def clean(self):
        super().clean()
        if self.aniversario.year >= 2022:
            raise ValidationError({f'aniversario': "O ano de nasicmento não pode ser maior que 2021."})

    def __str__(self):
        return self.nome
    
class Colecao(models.Model):
    nome = models.CharField(max_length=255, unique= True, verbose_name="Nome da Coleção:")
    descricao = models.TextField(blank= True, null=True, verbose_name="Descrição:")
    data_criacao = models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação:")
    data_atualizacao = models.DateTimeField(auto_now=True, verbose_name="Data de Atualização:")

    def __str__(self):
        return self.nome
    
    

templates/autores.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca - Autores</title>

    
    {% load static %}

    
    <link rel="stylesheet" href="{% static 'css/autores.css' %}">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>

<body>

    <nav style="margin-top: 0px !important;" class="navbar fixed-top">
        <div style="background: url('') no-repeat center center !important; background-size: 100% auto !important; border: 0; margin-top: -10px !important; height: 57px;" class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div style="background-color: transparent !important; border: 0; " class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div style="background-color: transparent !important;" class="offcanvas-body">
                    <aside>
                        
                        <ul class="lista-lateral">
                            <div class="div-perfil">
                                <i class="bi bi-person-circle"></i>
                                <a style=" color:#5a4d3e" href="{% url 'usuarios:perfil' %}">Olá, {{user.username}}</a>
                                <hr style="height: 3px; width:80%">
                            </div>
                            <li style="margin-left:15px; font-weight:600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'index' %}">LIVROS</a></li>
                            
                            <li style="margin-left:15px; font-weight:600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'autores' %}">AUTORES</a></li>
            <li style="margin-left:15px; font-weight:600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'colecoes' %}">COLEÇÕES</a></li>
            <li style="margin-left:15px; font-weight:600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'categorias' %}">CATEGORIAS</a></li>
                        </ul>
                        <div style="margin-bottom: 50px" class="div-logout">
                            <i class="bi bi-box-arrow-left"></i>
                            <a href="{% url 'usuarios:logout' %}">Sair</a>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </nav>

    <aside class="aside2">
        <ul class="lista-lateral">
            <div class="div-perfil">
                <i class="bi bi-person-circle"></i>
                <a style=" color:#5a4d3e" href="{% url 'usuarios:perfil' %}">Olá, {{user.username}}</a>
                <hr style="height: 3px; width:80%">
            </div>
            <li style="margin-left:15px; font-weight:600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'index' %}">LIVROS</a></li>
                            
            <li style="margin-left:15px; font-weight:600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'autores' %}">AUTORES</a></li>
            <li style="margin-left:15px; font-weight:600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'colecoes' %}">COLEÇÕES</a></li>
            <li style="margin-left:15px; font-weight:600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'categorias' %}">CATEGORIAS</a></li>
        </ul>
        <div class="div-logout">
            <i class="bi bi-box-arrow-left"></i>
            <a href="{% url 'usuarios:logout' %}">Sair</a>
        </div>
    </aside>


    <!-- Modal novo autor -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content"
                style="background: url('{% static 'images/card_modal.png' %}') no-repeat center center !important; background-size: 80% auto !important; height: 700px; border: 0; padding: 100px;">
                <div class="modal-body">
                    <div style="display: flex; align-items: end; justify-content: flex-end; width: 105%;">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <br>
                    <h4 style="font-family: MedievalSharp, cursive;
                    font-weight: bold;
                    font-style: normal;
                    color: #5a4d3e;">NOVO AUTOR+</h4>
                    <br>
                    <form class="form-addlivro" method="post">
                        {% csrf_token %}
                        <label for="{{ autor_form.nome.id_for_label }}">Nome do Autor:</label>
                        {{ autor_form.nome }}
                        
                        <label for="{{ autor_form.biografia.id_for_label }}">Biografia:</label>
                        {{ autor_form.biografia }}
                        
                        <label for="{{ autor_form.aniversario.id_for_label }}">Data de Aniversário:</label>
                        {{ autor_form.aniversario }}
                        
                        <label for="{{ autor_form.nacionalidade.id_for_label }}">Nacionalidade:</label>
                        {{ autor_form.nacionalidade }}
                        
                        <button name="salvar_autor" type="submit"><u>ADICIONAR</u></button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <main>
        <div class="main-actions">
            <h2>AUTORES</h2>
            {% if request.user.is_superuser %}
                            
            <button class="button-aplicar-filtros" style=" background: url('{% static 'images/card_button.png' %}') no-repeat center center !important;" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">NOVO AUTOR+</button>
                            {% endif %}
        </div>
        

        <div class="main-categorias">
            {% for autor in autores %}
            <div style="display:flex; justify-content: space-between; align-items:center; margin-top: 20px">   
                <h4>{{autor.nome}}</h4>
                {% if request.user.is_superuser %}
                <div class="main-icons">
                    <a style="color: #5a4d3e;" href="{% url 'editar_autor' autor.id %}">
                        <i style="color: #5a4d3e;" class="bi bi-pencil-square"></i> 
                    </a>
                    <a style="color: #5a4d3e;" href="{% url 'deletar_autor' autor.id %}">
                        <i  class="bi bi-trash3-fill"></i>
                    </a>
                </div>
                            
                            {% endif %}
            </div>
        <p>{{ autor.biografia }}</p>
        <span><strong>Nacionalidade:</strong> {{ autor.nacionalidade }}</span><br>
        <span><strong>Aniversário:</strong> {{ autor.aniversario }}</span><br>

        <strong>Livros:</strong>
        {% if autor.livros.all %}
            <ul>
                {% for livro in autor.livros.all %}
                    <li>{{ livro.nome }} ({{ livro.ano }})</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Este autor ainda não tem livros registrados.</p>
        {% endif %}
        
        <hr>
    {% endfor %}
        </div><br>
        
    </main>

</body>

</html>

templates/categorias.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biblioteca - Categorias</title>

    
    {% load static %}

    
    <link rel="stylesheet" href="{% static 'css/categorias.css' %}">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>

<body>

    <nav style="margin-top: 0px !important;" class="navbar fixed-top">
        <div style="background: url('') no-repeat center center !important; background-size: 100% auto !important; border: 0; margin-top: -10px !important; height: 57px;" class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div style="background-color: transparent !important; border: 0; " class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div style="background-color: transparent !important;" class="offcanvas-body">
                    <aside>
                        
                        <ul class="lista-lateral">
                            <div class="div-perfil">
                                <i class="bi bi-person-circle"></i>
                                <a style=" color:#5a4d3e" href="{% url 'usuarios:perfil' %}">Olá, {{user.username}}</a>
                                <hr style="height: 3px; width:80%">
                            </div>
                            <li style="margin-left:15px; font-weight: 600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'index' %}">LIVROS</a></li>
                            
                            <li style="margin-left:15px; font-weight: 600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'autores' %}">AUTORES</a></li>
            <li style="margin-left:15px; font-weight: 600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'colecoes' %}">COLEÇÕES</a></li>
            <li style="margin-left:15px; font-weight: 600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'categorias' %}">CATEGORIAS</a></li>
                        </ul>
                        <div style="margin-bottom: 50px" class="div-logout">
                            <i class="bi bi-box-arrow-left"></i>
                            <a href="{% url 'usuarios:logout' %}">Sair</a>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </nav>

    <aside class="aside2">
        <ul class="lista-lateral">
            <div class="div-perfil">
                <i class="bi bi-person-circle"></i>
                <a style=" color:#5a4d3e" href="{% url 'usuarios:perfil' %}">Olá, {{user.username}}</a>
                <hr style="height: 3px; width:80%">
            </div>
            <li style="margin-left:15px; font-weight: 600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'index' %}">LIVROS</a></li>
                            
            <li style="margin-left:15px; font-weight: 600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'autores' %}">AUTORES</a></li>
            <li style="margin-left:15px; font-weight: 600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'colecoes' %}">COLEÇÕES</a></li>
            <li style="margin-left:15px; font-weight: 600"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'categorias' %}">CATEGORIAS</a></li>
        </ul>
        <div class="div-logout">
            <i class="bi bi-box-arrow-left"></i>
            <a href="{% url 'usuarios:logout' %}">Sair</a>
        </div>
    </aside>


     <!-- Modal nova categoria -->
     <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content"
                style="background: url('{% static 'images/card_modal.png' %}') no-repeat center center !important; background-size: 80% auto !important; height: 700px; border: 0; padding: 100px;">
                <div class="modal-body">
                    <div style="display: flex; align-items: end; justify-content: flex-end; width: 105%;">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <br>
                    <h4 style="font-family: MedievalSharp, cursive;
                    font-weight: bold;
                    font-style: normal;
                    color: #5a4d3e;">NOVA CATEGORIA+</h4>
                    <br>
                    <form class="form-addlivro" method="post">
                        {% csrf_token %}
                        <label for="id_nome">Nome da Categoria:</label>
                        {{ categoria_form.nome }}
                    
                        <label for="id_descricao">Descrição:</label>
                        {{ categoria_form.descricao }}
                        
                        
                        <button name="salvar_categoria" type="submit"><u>ADICIONAR</u></button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>

    <main>
        <div class="main-actions">
            <h2>CATEGORIAS</h2>
            {% if request.user.is_superuser %}
                            
            <button class="button-aplicar-filtros" style=" background: url('{% static 'images/card_button.png' %}') no-repeat center center !important;" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">NOVA CATEGORIA+</button>
            {% endif %}
        </div>
        

        <div class="main-categorias">
            {% for categoria in categorias %}
            
             
            <div style="display:flex; justify-content: space-between; align-items:center; margin-top: 20px">   
                <h4>{{categoria.nome}}</h4>
                {% if request.user.is_superuser %}
                            
                <div class="main-icons">
                    <a style="color: #5a4d3e;" href="{% url 'editar_categoria' categoria.id %}">
                        <i style="color: #5a4d3e;" class="bi bi-pencil-square"></i> 
                    </a>
                    <a style="color: #5a4d3e;" href="{% url 'deletar_categoria' categoria.id %}">
                        <i  class="bi bi-trash3-fill"></i>
                    </a>
                </div>
                            {% endif %}
            </div>
            <hr style="margin-top: -7px">
            <span>{{categoria.descricao}}</span>
            {% endfor %}
        </div><br>
        
    </main>

</body>

</html>

templates/deletar_autor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}

    <title>Deletar Autor</title>
    <link rel="stylesheet" href="{% static 'css/deletar_autor.css' %}">
</head>
<body >
    <div style="background: url('{% static 'images/fundo_edit.png' %}') no-repeat center center;">
            <div  style="background: url('{% static 'images/card_modal.png' %}') no-repeat center center !important; background-size: 100% auto !important; height: 420px; border: 0; padding: 75px; width:250px;" class="form-addlivro" method="post">
                <h4>Tem certeza que deseja excluir?</h4>
                <span> {{autor.nome}}</span><br>
                <form method="post">
                    <a href="{% url 'autores' %}"> Cancelar </a>
                    {% csrf_token %}
                    <button name="confirmar" type="submit">
                        Confirmar
                    </button>
                </form>
                
            </div>
    </div>
    
</body>
</html>

templates/editar_autor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}

    <title>Editar Autor</title>
    <link rel="stylesheet" href="{% static 'css/editar_autor.css' %}">
</head>
<body >
    <div style="background: url('{% static 'images/fundo_edit.png' %}') no-repeat center center;">
            <form  style="background: url('{% static 'images/card_modal.png' %}') no-repeat center center !important; background-size: 100% auto !important; height: 420px; border: 0; padding: 75px; width:250px;" class="form-addlivro" method="post">
                <h4 style="font-family: MedievalSharp, cursive; font-weight: bold; font-style: normal; color: #5a4d3e;">EDITAR AUTOR</h4>
                {% csrf_token %}
                <label for="id_nome">Nome da Categoria:</label>
                {{ form.nome }}
                
                <label for="id_biografia">Biografia:</label>
                {{ form.biografia }}
                <label for="id_aniversario">Aniversário:</label>
                {{form.aniversario}}
                <label for="id_nacionalidade">Nacionalidade:</label>
                {{form.nacionalidade}}
                <br><br>
                <button name="salvar_autor" type="submit"><u>Salvar Alterações</u></button>
                
            </form>
    </div>
    
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bibioteca- Livros!</title>

    
    {% load static %}

    
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>

<body>

    <nav style="margin-top: 0px !important; " class="navbar fixed-top">
        <div style="background: url('') no-repeat center center !important; background-size: 100% auto !important; border: 0; margin-top: -10px !important; height: 57px;" class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                
            </button>
            <div style="background-color: transparent !important; border: 0;" class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div style="background-color: transparent !important;" class="offcanvas-body">
                    <aside>
                        <ul class="lista-lateral">
                            <div class="div-perfil">
                                <i class="bi bi-person-circle"></i>
                                <a style=" color:#5a4d3e" href="{% url 'usuarios:perfil' %}">Olá, {{user.username}}</a>
                                <hr style="height: 3px; width:90%">
                            </div>
                            <li style="margin-left:10px; font-weight:600">BIBLIOTECA</li>
                            <li style="margin-left:25px; font-weight:400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'index' %}">LIVROS</a></li>
                            <li style="margin-left:25px; font-weight: 400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'autores' %}">AUTORES</a></li>
                            <li style="margin-left:25px; font-weight: 400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'colecoes' %}">COLEÇÕES</a></li>
                            <li style="margin-left:25px; font-weight: 400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'categorias' %}">CATEGORIAS</a></li>
                            <li style="margin-left:10px; font-weight:600">ATIVIDADES</li>
                            <li style="margin-left:25px; font-weight:400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'atividades:reservas' %}">RESERVAS</a></li>
                            <li style="margin-left:25px; font-weight: 400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'atividades:favoritos' %}">FAVORITOS</a></li>
                            <li style="margin-left:10px; font-weight:600">INFORMAÇÕES</li>
                            <li style="margin-left:25px; font-weight:400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'sobre' %}">SOBRE</a></li>
                        </ul>
                        <div style="margin-bottom: 50px" class="div-logout">
                            <i class="bi bi-box-arrow-left"></i>
                            <a href="{% url 'usuarios:logout' %}">Sair</a>
                        </div>
                    </aside>
                    
                </div>
            </div>
        </div>

    </nav>

    <aside class="aside2">
        <ul class="lista-lateral">
            <div class="div-perfil">
                <i class="bi bi-person-circle"></i>
                <a style=" color:#5a4d3e" href="{% url 'usuarios:perfil' %}">Olá, {{user.username}}</a>
                <hr style="height: 3px; width:80%">
            </div>
            <li style="margin-left:10px; font-weight:600">BIBLIOTECA</li>
                            <li style="margin-left:25px; font-weight:400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'index' %}">LIVROS</a></li>
                            <li style="margin-left:25px; font-weight: 400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'autores' %}">AUTORES</a></li>
                            <li style="margin-left:25px; font-weight: 400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'colecoes' %}">COLEÇÕES</a></li>
                            <li style="margin-left:25px; font-weight: 400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'categorias' %}">CATEGORIAS</a></li>
                            <li style="margin-left:10px; font-weight:600">ATIVIDADES</li>
                            <li style="margin-left:25px; font-weight:400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'atividades:reservas' %}">RESERVAS</a></li>
                            <li style="margin-left:25px; font-weight: 400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'atividades:favoritos' %}">FAVORITOS</a></li>
                            <li style="margin-left:10px; font-weight:600">INFORMAÇÕES</li>
                            <li style="margin-left:25px; font-weight:400"><a style="text-decoration:none; color: #5a4d3e" href="{% url 'sobre' %}">SOBRE</a></li>
        </ul>
        <div class="div-logout">
            <i class="bi bi-box-arrow-left"></i>
            <a href="{% url 'usuarios:logout' %}">Sair</a>
        </div>
    </aside>

</body>

</html>